### ISSUE TITLE
Allow PNGs as ground truths of jpeg images.

### ISSUE THREAD

**Issue by tadbeer** [mdbloice/Augmentor#104]
I mostly create my ground truth images, for my images in my dataset, manually by painting with hand in an image editor like MS Paint. In order to later extract the ground truth information algorithmically from them, the extraction logic (made for eg. in OpenCV/skimage) works best when the GT image is in a lossless format like png. This is because I can direct the algo to locate the exact RGB value at a particular pixel, which is difficult if the image is in a compressed format like JPEG.

Could you please just allow png images as ground truth images, with the same names as original images, to be read in the augmentor pipeline and then later save the augmented image as a png too?

**Comment by kekeller** [comment]
I would also love this. Using a jpg as a mask doesn't work so well if you need specific pixel values for the training. 

I got around it by converting the image and the mask to tif images.

**Comment by mdbloice** [comment]
Hi @tadbeer, @kekeller a new feature just added should let you do that, see <https://github.com/mdbloice/Augmentor/blob/master/notebooks/Multiple-Mask-Augmentation.ipynb> for details. Basically a new DataPipeline class has been added that is more flexible for when you are using ground truth data of different formats and so on.
