### ISSUE TITLE
Crop by size give mismatch results between the groundtruth and original image.

### ISSUE THREAD

**Issue by npmhung** [mdbloice/Augmentor#111]
When I set the centre property to False, the groundtruth and the original image are cropped at different locations while the expected behavior is that both images are cropped at the same location.

**Comment by mdbloice** [comment]
Hi @npmhung, yes indeed you are right, there is a bug in the `Crop` class that I have just found. Thanks for pointing this out, I will fix this ASAP.

**Comment by mdbloice** [comment]
@npmhung, I just uploaded a new version of Augmentor (0.2.2) to PyPI so if you upgrade this should now be fixed (`pip install Augmentor --upgrade`). 
M.
