### ISSUE TITLE
How to crop a skewed image without losing content?

### ISSUE THREAD

**Issue by bezigon** [mdbloice/Augmentor#115]
Similar to #66. When using the skewing function the automatic crop removes some of the content of the original image.

Here is an example:

Original:
![algorithm1demonstration1](https://user-images.githubusercontent.com/771853/40533649-17016dd8-600c-11e8-91d1-81cb4087c5de.JPG)
Skewed:
![source_original_algorithm1demonstration1 jpg_6b8c27fe-dc27-4dcd-aaab-cdbb5808f66e](https://user-images.githubusercontent.com/771853/40533682-32ca1574-600c-11e8-9727-41b54bcd5842.PNG)

Is there a way to avoid this?

**Comment by mdbloice** [comment]
HI @bezigon, well no not really because by adding this angle you will lose some of the image if you maintain the image size and dimensions, take a look at *Skew Type 1* from the README file, you'll see what is lost when any of these types of operations are performed...

**Comment by mdbloice** [comment]
Actually, it seems you used a tilt operation, perhaps an operation such as Skew Type 1 would be better as you will only "lose" the top portion of the image...

**Comment by bezigon** [comment]
I've forked code for my purposes, thanks anyway!

**Comment by ayumiymk** [comment]
Hi, could you please share the code to solve this question? Thank you!
