### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by sliawatimena** [mdbloice/Augmentor#127]
I am using Python 3.6.5, Ipython 6.4.0, try to import Augmentor, pillow 5.1.0
when I type: 
from PIL import Image, 

it generates error.

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-458a74577dcf> in <module>()
----> 1 import Augmentor

E:\Anaconda3\envs\opencv\lib\site-packages\Augmentor\__init__.py in <module>()
     12 """
---> 14 from .Pipeline import Pipeline, DataFramePipeline
     16 __author__ = """Marcus D. Bloice"""

E:\Anaconda3\envs\opencv\lib\site-packages\Augmentor\Pipeline.py in <module>()
     16 from builtins import *
---> 18 from .Operations import *
     19 from .ImageUtilities import scan_directory, scan, scan_dataframe, AugmentorImage

E:\Anaconda3\envs\opencv\lib\site-packages\Augmentor\Operations.py in <module>()
     25 from builtins import *
---> 27 from PIL import Image, ImageOps, ImageEnhance
     28 import math
     29 from math import floor, ceil

E:\Anaconda3\envs\opencv\lib\site-packages\PIL\Image.py in <module>()
     58     # Also note that Image.core is not a publicly documented interface,
     59     # and should be considered private and subject to change.
---> 60     from . import _imaging as core
     61     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     62         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.
```

how to correct this problem? thanks.

**Comment by mdbloice** [comment]
Hi @sliawatimena, it looks like Pillow needs a DLL that doesn't match up to whatever you have installed on your system.

Perhaps try what is suggested here: <https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found> 

Let me know if this helps. 
M.

**Comment by sliawatimena** [comment]
> conda update --all 
(still in progress)

another suggestion are: 
a. to install Pillow 5.2.0 (not 5.1.0)

b. removing pillow using conda and installing using pip
$ conda remove pillow
$ pip install pillow

**Comment by mdbloice** [comment]
Yeah, I test against the latest version of Pillow whatever that is on PyPI. Looking at the Travis CI logs I see that was version `pillow-5.1.0` for Python 3.6 so I kinda doubt that's the problem you are having. Anyway, let me know.
