### ISSUE TITLE
Cannot detect synthesized images

### ISSUE THREAD

**Issue by bottlecrasher** [mdbloice/Augmentor#128]
I tried to augment synthesized image from PIL library. But Augmentor failed to detect my image files. I tried jpeg and png file extension and ubuntu authority, etc, but there is no idea what is going wrong. I already used Augmentor to other datasets, so I strongly assure that library installed correctly. Have anyone experienced the same thing? 

Next is the code that how I created the Image. 

text_canvas = Image.new("RGB", (img_size, img_size), (0,0,0))
draw = ImageDraw.Draw(text_canvas)
font_size = 96
font = ImageFont.truetype(font, font_size)
draw.text((0,0), char, font = font, fill = "#202020")
text_canvas.save(filename, "JPEG", optimizer= True)

**Comment by mdbloice** [comment]
Hi @bottlecrasher, really not sure what might be the issue there. What error does Augmentor itself throw when you try to use these images that you have saved? 
Normally anything created by PIL/Pillow will be read fine by Augmentor...

**Comment by bottlecrasher** [comment]
Thanks for your reply. 
Yes, The problem is when I create initialize pipeline object, it cannot detect the synthesized images in the folder. 
 
Error Message :
**Output directory set to ./data/0x21/output.Initialised with 0 image(s) found.**
  File "/home/kimjonghyuk/anaconda3/envs/facenet/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-7551011a824c>", line 71, in <module>
    main()
  File "<ipython-input-3-7551011a824c>", line 68, in main
    p.sample(100)
  File "/home/kimjonghyuk/anaconda3/envs/facenet/lib/python3.6/site-packages/Augmentor/Pipeline.py", line 311, in sample
    raise IndexError(**"There are no images in the pipeline. "**
IndexError: There are no images in the pipeline. Add a directory using add_directory(), pointing it to a directory containing images.


If i throw the other images from internet, Augmentor works greatly on downloaded file, but still cannot detect or work on the synthesized image. I tried JPEG and PNG with several channels, but all of the fails. I hope this issue will going to be solved soon.

Anyway, Good job for creating this! It will very helpful to all of  deep learning practitioneer.

**Comment by bottlecrasher** [comment]
I attach my one of image here. I tried right now, but also failed.

![0x21_851mkpop_001](https://user-images.githubusercontent.com/28390993/43557621-6fb3a486-9640-11e8-9694-bf838973b26e.jpeg)

**Comment by mdbloice** [comment]
Right, the files need extensions otherwise the scan won't find any images in the directory you point to. Glad you sorted it out. 
M.
