### ISSUE TITLE
Image to Image issue

### ISSUE THREAD

**Issue by FiReTiTi** [mdbloice/Augmentor#132]
Hi,
I have RGB input images and a binary mask as ground truth. So I used the code provided as example:

    p = Augmentor.Pipeline("/path/to/images")
    p.ground_truth("/path/to/ground_truth_images")

First thing, it does not work if I give a relative path for the images, it has the be the full paths for both directories of images.

Then, I tried to use it with Keras:

    gen = p.keras_generator(batch_size=5, scaled=False)

But it returns the input images and an array of labels containing only 0, and the shapes confirm it:

    Input (5, 256, 256, 3)
    Ground Truth (5, 1)

What is wrong?

**Comment by mdbloice** [comment]
Yeah @FiReTiTi, currently the generators do not support masks. But that's gonna change in the next version also :-)

**Comment by kkirtac** [comment]
Hi, is it supported now in 0.2.3 version?

**Comment by mdbloice** [comment]
Hi @kkirtac, @FiReTiTi yes generators now support masks since 0.2.3, see the ![Multiple-Mask-Augmentation.ipynb](https://github.com/mdbloice/Augmentor/blob/master/notebooks/Multiple-Mask-Augmentation.ipynb) demonstration notebook for details.
