### ISSUE TITLE
Pipeline does not work

### ISSUE THREAD

**Issue by simongeek** [mdbloice/Augmentor#138]
Hi!

When I want to run Pipeline such as below:
```
import Augmentor
pathROI = 'path/to/ROI'
pathMask = 'path/to/Mask'

p = Augmentor.Pipeline(pathROI)
p.ground_truth(pathMask)
p.rotate(probability=1, max_left_rotation=5, max_right_rotation=5)
p.sample(2000)
```

I got error in line p.sample(2000):

> AttributeError: 'NoneType' object has no attribute 'mode'

How to fix it?

I'm working on OSX system.

**Comment by mdbloice** [comment]
Hi @simongeek, it seems to me like the no images were found. You can call `p.status()` to see what images are associated with the current pipeline object, you'll get something like this printed to the console:

```
>>> p.status()
Operations: 0
Images: 24
Classes: 4
	Class index: 0 Class label: original 
	Class index: 1 Class label: pigment-network 
	Class index: 2 Class label: pigment-network-overlayed 
	Class index: 3 Class label: segmentation 
Dimensions: 1
	Width: 1022 Height: 767
Formats: 2
	 PNG
	 JPEG

You can remove operations using the appropriate index and the remove_operation(index) function.
```

M.

**Comment by simongeek** [comment]
It's now correct! Thanks! 👍
