### ISSUE TITLE
about label 255

### ISSUE THREAD

**Issue by zmghub** [mdbloice/Augmentor#141]
when my label contain this value 255,for example,my label is x,and np.unique(x) is [0,1,255],this result outputed by the augmentor may have some other value such as [0,1,2,3,4,5,……],and i have test rotate,skew,shear,zoom,distortion,all i get are same.
in addition to this,i find out it is random,when the code is same,the two result i get from two execution is different, in other word,i get three bad sample in the first execution,and i may get five bad sample in the second execution.

**Comment by mdbloice** [comment]
Hi @zmghub, yeah your labels will need to be a list starting at 0 and increasing in increments of 1.
