### ISSUE TITLE
how to add noise

### ISSUE THREAD

**Issue by pkb14197** [mdbloice/Augmentor#145]
Hi,

can you please let me know how to add noise in images? I find you have a file named "test_Gaussion.py", is it related to a noise method?

**Comment by mdbloice** [comment]
Hi @pkb14197, no you want to use the `random_erasing()` method with a Pipeline object. 

You can find the  `random_erasing()` function's documentation [here](https://augmentor.readthedocs.io/en/master/code.html#Augmentor.Pipeline.Pipeline.random_erasing). 

A working example might look something like:

```python
import Augmentor
p = Augmentor.Pipeline("/path/to/images")
# Add random erasing
p.random_erasing(probability=1, rectangle_area=0.33)
# Sample 100 images with random erasing
p.sample(100)
```
