### ISSUE TITLE
Maths behind the operations

### ISSUE THREAD

**Issue by Kelkka7** [mdbloice/Augmentor#157]
First off, Augmentor is a very nice package - especially like the easy to read code, clear explanations and the sheer number of operations.

Still, it would be nice to see the maths behind your operations, or at least a link to a paper that outlines them. I'm particularly interested in rotate_random_90, random_distortion, shear, and resize operations, but I'm likely to experiment with other operations too. I'm not a mathematician or a computer scientist, so I have no starting point for the maths, but I'm writing a PhD thesis in which I'm using machine learning so I need to be quite detail oriented.  Can you help?

**Comment by mdbloice** [comment]
Hi @Kelkka7, glad you like Augmentor. Well, a lot of stuff is just from Wikipedia's articles on affine transformations, e.g. [https://en.wikipedia.org/wiki/Affine_transformation](https://en.wikipedia.org/wiki/Affine_transformation)

The article above has a few very useful overview graphics, such as: [2D_affine_transformation_matrix.svg](https://en.wikipedia.org/wiki/Affine_transformation#/media/File:2D_affine_transformation_matrix.svg) 

The random distortion operation is from a paper that was published quite a few years ago: [https://www.microsoft.com/en-us/research/wp-content/uploads/2003/08/icdar03.pdf](https://www.microsoft.com/en-us/research/wp-content/uploads/2003/08/icdar03.pdf) (called Elastic Distortions in the paper). 

As for the sheer and resize etc. operations, they are either built in PIL (Python Imaging Library) functions or they are done using NumPy, according to what is contained in that Wikipedia affine transformation article. 

I hope this helps!

**Comment by Kelkka7** [comment]
@mdbloice Thanks for the links! That should clear things up.
