### ISSUE TITLE
Progressbar for pipeline and using image.convert() for forcing RGB/L/..

### ISSUE THREAD

**Issue by bedapudi6788** [mdbloice/Augmentor#168]
Hi @mdbloice thanks for this awesome repo. I have two simple feature suggestions (I am happy to add a pull request for these if you want these implemented).
1. Since pipeline creation takes a significant amount of type if we have lot of images in the folder I think it would be good to have a progressbar to show the status. 
2. Sometimes, when dealing with large datasets, images of different types can be present (RGB, grayscale etc) and since pillow reads in default format, .reshape will cause an error in keras_generator. I think it would be good to have a option to convert all images into a userdefined format. (RGB/ L etc). We can do this using .convert() in Pillow.

I will be happy to add a pull request with these features if you want to implement them.

**Comment by mdbloice** [comment]
Hi @bedapudi6788, glad you like the library - yeah, if you use Augmentor in a console it does indeed show a progress bar, using [tqdm](https://github.com/tqdm/tqdm) and actually it should show in a Python notebook as well, as long as you are using the `sample()` function anyway. 
As for your second point, yes sometimes some formats cause errors - are there any specific examples of these errors you can show me? 
If you feel like making a PR to address some issue you have had with file formats, please do! 
M.

**Comment by bedapudi6788** [comment]
@mdbloice The progressbar issue I mentioned is while using keras_generator.
Augmentor.Pipeline(folder) this takes a considerable time (hours) when dealing with lot of images (I am currently using with 5 lakh images) and I am not seeing a progressbar for this. https://github.com/mdbloice/Augmentor/blob/e6ef7bc73d5790c864d3977f7cc4e2e9905c03f5/Augmentor/Pipeline.py#L184 This is the loop, where I am suggesting to add the for loop.

For the second point, If some dataset contains Grayscale images along with RGB images, the training will pipeline will fail at .reshape(32, 32, 3).

**Comment by mdbloice** [comment]
@bedapudi6788 ah yes, ok for generators there is no progress bar mainly because the generator itself does not control or know the number of samples that need to be generated, unlike `sample()` where I can specify the number of images to be created and therefore can control the "length" of the status bar. 

Ok as for the second point, if you want to think of a solution and propose it via a PR I would be happy to take a look! 

Sorry for the delay in replying, work duties have kept me away. 
M.
