### ISSUE TITLE
p.resize jpg save

### ISSUE THREAD

**Issue by ak9250** [mdbloice/Augmentor#170]
output files are not saved as jpg, I tested with one jpg and one png, they are the same in the outputs folder

**Comment by mdbloice** [comment]
Hi @ak925, thanks for making the issue - could you post some code that reproduces that? I think it really should save in the format that you pass, so I'd be curious how this happened to you. Thanks.

**Comment by ak9250** [comment]
@mdbloice Hi, want i mean to say is wouldnt it be better to save all resized images as jpegs to save space and will have consistency in the dataset. I thought p.resize does this by default, maybe a flag to use one format for all resized images?

**Comment by mdbloice** [comment]
@ak9250, you can set the save format when initialising a pipeline object:
```python
import Augmentor
p = Augmentor.Pipeline("/path/to/images", save_format="JPEG")
```
See the docs at [https://augmentor.readthedocs.io/en/master/code.html#Augmentor.Pipeline.Pipeline](https://augmentor.readthedocs.io/en/master/code.html#Augmentor.Pipeline.Pipeline)

**Comment by ak9250** [comment]
thanks!
