### ISSUE TITLE
Is there a way or option which I can use not to perform shuffling when I use `aug_pipeline.sample(int(num_of_sample))`?

### ISSUE THREAD

**Issue by youngminpark2559** [mdbloice/Augmentor#172]
HI. It looks like `aug_pipeline.sample(int(num_of_sample))` outputs images and their masks (or labels) in shuffled order by default.

But I hope to have them from the output of aug_pipeline.sample(int(num_of_sample)) in the status of order which are set before going to Augmentor pipeline.

**Comment by mdbloice** [comment]
Hi @youngminpark2559 no currently not, however this has been requested before so I will look into implementing this in an upcoming version.

**Comment by youngminpark2559** [comment]
@mdbloice Thanks for considering that functionality. Hope to see it in Augmentor.

**Comment by mdbloice** [comment]
@youngminpark2559 sure thing! I will try to get it in to the next version.
