### ISSUE TITLE
Why is the output directory always relative to input?

### ISSUE THREAD

**Issue by AdityaSoni19031997** [mdbloice/Augmentor#178]
https://github.com/mdbloice/Augmentor/blob/master/Augmentor/Pipeline.py#L143
>abs_output_directory = os.path.join(source_directory, output_directory)

This isn't exactly what everyone wants, what if you don't have permissions to write to the input directory??

A simple solution would be to just add a flag to ask the user if wants it relative to the i/p or not?

**Comment by Mahi-Mai** [comment]
I would also prefer to define this myself.
