### ISSUE TITLE
Crashes when OOM

### ISSUE THREAD

**Issue by tr1pzz** [mdbloice/Augmentor#193]
I've experienced several crashes of my VM due to running out of cache memory.

My machine crashed with 8 CPU's & 32Gb memory after sampling 6000/20000 images (I watched the cache memory slowely build up..)

**Comment by tr1pzz** [comment]
I've solved this using the following snippet:

```
...

def create_pipeline(seed_id):
    p = Augmentor.Pipeline(input_folder, output_folder, save_format="JPEG")
    p.set_seed(seed)
    p.add_operation(...)
    ...
    return p

total_images_to_sample = 20000
max_at_once = 2000

iterations = int(total_images_to_sample/max_at_once)
for seed_id in range(iterations):
    p = create_pipeline(seed_id)
    p.sample(max_at_once)
    del p
```

**Comment by mdbloice** [comment]
Hi @tr1pzz - there is also a way to disable multi-threading altogether:
```
p.sample(n, multi_threaded=False)
```
Anyway, I will investigate the issue with the cache, thanks for taking the time to make the issue.
