### ISSUE TITLE
Summary functions.

### ISSUE THREAD

**Issue by mdbloice** [mdbloice/Augmentor#2]
Both `ImageSource` and `Pipeline` object require functions, named `summary` that output details regarding that object's state. For the `ImageSource` class that is a run down of the image sources that are currently loaded. The `Pipeline`'s summary should output the operations that have been added so far, 

Also, the `ImageSource` and `Pipeline`'s `summary` function should output tables in Markdown valid syntax. This would mean that if the package is being used in Jupyter, a nicely formatted table will render when `summary` is called. Also, they would look fine in a REPL interpreter. 

It should output valid Markdown such as the following output from an `ImageSource` object:

```
| Summary           |                    |
|:-----------------:|--------------------|
| Image count       | 120                |
| Dimensions        | 480x480 (120)      |
| Aspect ratio(s)   | 1:1                |
| File type(s)      | 1                  |
| File extension(s) | BMP                |
| File format(s)    | Grayscale          |
```

Example rendered output for an ImageSource object:

| Summary |  |
| :-: | --- |
| Image count | 120 |
| Dimensions | 480x480 (120) |
| Aspect ratio(s) | 1:1 |
| File type(s) | 1 |
| File extension(s) | BMP |
| File format(s) | Grayscale |

Note that the idea is that `summary` provides an overview of the interesting properties of the data source. For example it could be the case that all images are of different size, in that situation it wouldn't be very informative to print every size there is. However, if it is still the case that all images are of the same aspect ratio than that information is interesting and worth printing.

**Comment by lradacher** [comment]
We are still working on File format(s) here.
Basically, we are not sure what the results of "File format(s)" should be.
Would it be possible to provide some more examples on this matter?

**Comment by mdbloice** [comment]
Well, the table should just output the types of file formats that a folder contains. For example, it would be useful to know if all the images were grayscale, black and white, or colour (RGB, etc.) - or a mixture of these. This is important because at the very least you want to have images of the same format for input into a neural network (therefore you might want to make all images grayscale). Also, colour RGB images contain three layers, one layer for each colour, and therefore have a matrix of shape `[800x600x3]` for an `800x600` image. Grayscale and Black&White images do not have three layers and therefore have a matrix shape of `[800x600x1]`.

**Comment by lradacher** [comment]
this issue should be finished
