### ISSUE TITLE
augmented image and corresponding mask does not match

### ISSUE THREAD

**Issue by eemberda** [mdbloice/Augmentor#205]
Hi. I would like to ask for assistance. I tried to use Augmentor on the ISBI2012 dataset at https://imagej.net/Segmentation_of_neuronal_structures_in_EM_stacks_challenge_-_ISBI_2012 with the codes below. However, the output images and ground truths don't match.

![isbi](https://user-images.githubusercontent.com/1371096/69838024-97d10200-128c-11ea-87fe-5ebad03e41b0.PNG)

`p = Augmentor.Pipeline(ISBI2012_TRAIN_PATH+"/images")`
`p.ground_truth(ISBI2012_TRAIN_PATH+"/gt")`
`p.zoom_random(probability=0.5, percentage_area=0.8)`
`p.sample(640)`

**Comment by mdbloice** [comment]
Hi @eemberda, thanks for opening the issue, yes that's a bug and will be fixed today. I will write a message here once you can update via pip. 
Thanks again for pointing it out (and apologies for the delay). 
M.

**Comment by mdbloice** [comment]
Hi again @eemberda, the version on PyPI (version 0.2.7) now contains a fix for the issue you were having. You can update Augmentor using: `pip install Augmentor --upgrade`

**Comment by eemberda** [comment]
Thank you very much.

**Comment by mdbloice** [comment]
Sure thing. If you still encounter problems, just re-open the issue or open a new one. 
M.
