### ISSUE TITLE
Would you consider to extend Augmentor in 3D image segmentation?

### ISSUE THREAD

**Issue by Limingxing00** [mdbloice/Augmentor#219]
Hi, would you consider to extend Augmentor in 3D? I work in the biomedical image segmentation. In this field, we usually meet 3-D MRI, CT images. While, there is no convenient tool to augment 3D images for the segmentation tasks. I just used your tool, I feel very easy to use.

Best.

**Comment by nwschurink** [comment]
@Limingxing00 you could use [TorchIO](https://github.com/fepegar/torchio) which is specifically focussed on 3D medical image augmentation

**Comment by Limingxing00** [comment]
Thank you! It looks interesting.
