### ISSUE TITLE
Grayscale class

### ISSUE THREAD

**Issue by chronchi** [mdbloice/Augmentor#23]
I've been trying to add the grayscale option to the pipeline, as said in the documents, but when I do it shows the following error.
`>>> p.greyscale(probability=1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Pipeline' object has no attribute 'greyscale'`

I'm using Python 2.7.12.

**Comment by mdbloice** [comment]
Try the latest version on PyPI, version 0.1.2 - such issues should be fixed in that version.

**Comment by chronchi** [comment]
It worked, thanks!
