### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'Image'

### ISSUE THREAD

**Issue by ccl-private** [mdbloice/Augmentor#235]
follow "https://augmentor.readthedocs.io/en/master/userguide/extend.html#using-non-pil-image-objects" and face error above.

**Comment by mdbloice** [comment]
> I have overcome this problem just now. This is because the parameter of function perform_operation "image" is a list(). ![image](https://user-images.githubusercontent.com/36214675/137453535-a3ed24c7-ef41-46b5-94e5-097868a94315.png) add a for loop, it worked.

Yes indeed, this is not clear from that part of the documentation and is out of date. The `perform_operation()` function expects a list of images to be returned, even if only one image is returned.  

Thanks for taking the time to clear this up.
