### ISSUE TITLE
OSError: cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by ccl-private** [mdbloice/Augmentor#237]
![image](https://user-images.githubusercontent.com/36214675/137452071-340cdad1-5380-411c-86a1-f32f92f43507.png)

**Comment by mdbloice** [comment]
> After I read and rewrite all the images into .jpg files use OpenCV. The problem was solved. Maybe PIL does not have the ability to handle RGBA images by default set.

I will look in to this. Other functions support RGBA, and the `random_erasing()` function should also work with RGBA images, so I will have a look and see if I can fix this.
