### ISSUE TITLE
Random Ereasing areas too big

### ISSUE THREAD

**Issue by tanzerlana** [mdbloice/Augmentor#242]
Hello!

when using random erasing i cant go below 0.11 size. 11% of the size is too big for me, i would need a tenth of this. can this be adapted somehow? 

thank you!

best regards 

Igor

**Comment by tanzerlana** [comment]
Hello! thanks for your kind answer..

for my application I would need them to be between 0.01 and 0.1 as I am adding multiple labels it fills up too much and does not simulate our real world scenario

Thank you!

**Comment by mdbloice** [comment]
Hi again @tanzerlana - if you update Augmentor using pip you should be able to now use values between 0.01 and 1. 

Let me know if it's now working as you'd expect!

**Comment by tanzerlana** [comment]
Greaaaat! Thank you! Will test it asap


Von: Marcus D. Bloice ***@***.***>
Gesendet: Mittwoch, 27. April 2022 11:39
An: mdbloice/Augmentor ***@***.***>
Cc: Igor Masin - Tanzer Maschinenbau GmbH ***@***.***>; Mention ***@***.***>
Betreff: Re: [mdbloice/Augmentor] Random Ereasing areas too big (Issue #242)


Hi again @tanzerlana<https://github.com/tanzerlana> - if you update Augmentor using pip you should be able to now use values between 0.01 and 1.

Let me know if it's now working as you'd expect!

**Comment by tanzerlana** [comment]
@mdbloice i did not forget you, i am at home in quarantene and will be back on monday to test it.
