### ISSUE TITLE
Question - Does it updated the labels too?

### ISSUE THREAD

**Issue by tanzerlana** [mdbloice/Augmentor#243]
Hello! 
If I have a bunch of already labeled images (yolo - labeling) and let augmentor rotate and flip the image, can I somehow tell it to update the label files too? If yes, how?

Thank you!

**Comment by tanzerlana** [comment]
@mdbloice ok thank you.. would be a cool feature tough, else I have to re-label 2000 images.. but thank you anyway, i will try to come up with something

**Comment by mdbloice** [comment]
I have thought about adding such a feature before, but the way Augmentor was designed would mean a lot of refactoring of code so I never got around to it... 
Hopefully you'll find a way to do it without having to do it manually :)
