### ISSUE TITLE
Feeding Pipeline with numpy array

### ISSUE THREAD

**Issue by ahmetkucuk** [mdbloice/Augmentor#25]
The library looks pretty good. I would like to ask about a feature.

In addition to reading from directory and writing to directory, Is it possible to add a feature that can read from numpy array and returns augmented numpy array images?

**Comment by mdbloice** [comment]
Hi, 
That is a feature I eventually want to add, but right now it is not a top priority. Having said that, I will try to get something like that done for the next release, so I will leave this open till then. Sorry I can't be any more helpful right now...

**Comment by devforfu** [comment]
Is this one still on the list to be implemented?

**Comment by mdbloice** [comment]
Hi @devforfu, sorry I missed this message completely - yeah this functionality is now included, see <https://github.com/mdbloice/Augmentor/blob/master/notebooks/Augmentor_Keras_Array_Data.ipynb> for an example using MNIST and Keras. Basically there is a generator function that allows you to pass array data and it returns array data for use with Keras, but there is also a function that allows you to use Torch.
