### ISSUE TITLE
how to install this by anaconda

### ISSUE THREAD

**Issue by Jayhello** [mdbloice/Augmentor#38]
how to use conda install this lib
my default python interpreter is anaconda, if i use pip install this lib I can't use it
I use pycharm(backend by anaconda as interpreter)

**Comment by mdbloice** [comment]
Hi,
I'm really not sure why using conda would influence a pip install. Augmentor is not listed by conda so it is not possible to install with conda, only pip. I think however, to be able to install packages using both pip and conda, then pip should have itself been installed by conda. Does that help? 
M.
