### ISSUE TITLE
This comparison statement seems not right. The warning message is shown even if the image format is one of the two formats.

### ISSUE THREAD

**Issue by jrkwon** [mdbloice/Augmentor#40]
https://github.com/mdbloice/Augmentor/blob/06ac3331987c3a1c8b23f4667ddd50b785cd3dc0/Augmentor/Pipeline.py#L337

**Comment by mdbloice** [comment]
Hi,
Thanks for pointing this out. Yes, indeed that is not going work, I've fixed it now with the latest commit, 
M.

**Comment by jrkwon** [comment]
Thanks a lot. I use your Augmentor from 0.1.3, and the 0.1.4 version has a new function that I needed. It is a blast. I really enjoy to use it.

**Comment by mdbloice** [comment]
Thanks, your encouraging words are appreciated! P.S. the issue you pointed out should be fixed now in version 0.1.5 on PyPI, so updating will using `pip` will get rid of that warning. 
M.
