### ISSUE TITLE
Adding black_and_white to the pipeline should force a lossless format (Not JPEG)

### ISSUE THREAD

**Issue by luis1761** [mdbloice/Augmentor#49]
Currently, even if you specify a black and white operation but don't change the default picture format (.jpeg) the resulting picture contains values besides 0 and 255 due to compression.

To be clear black_and_white is not malfunctioning, changing to a lossless format (.png for example) when creating the pipeline fixes the problem.

**Comment by mdbloice** [comment]
Hi there, thanks for opening the issue - yes that is a good point, I'll need to look into that and get back to you. 
M.

**Comment by luis1761** [comment]
Thank you for the answer. What a useful tool you created, thanks.

**Comment by mdbloice** [comment]
@luis1761 in the latest version (0.2.0) Augmentor will now use a lossless file if the original file was lossless. So if the original file is a PNG file, then the augmented files will also automatically be saved as PNG files. I think this might solve what you were mentioning here.
