### ISSUE TITLE
not an issue - potential break through in 3d Point cloud scanning inference

### ISSUE THREAD

**Issue by johndpope** [mdbloice/Augmentor#50]
I watched this video this morning on 3d point cloud + ARKit
https://www.youtube.com/watch?v=kupq1C41XcU&feature=youtu.be
and it seems like a trained Augmentor model could help bridge the inference here in conjunction with trained model. Not sure if you agree, or if this is the correct repo for this - perhaps it is a new project.

<img width="326" alt="screen shot 2017-10-03 at 9 42 19 am" src="https://user-images.githubusercontent.com/289994/31128239-2db72202-a81f-11e7-8070-adac61d49382.png">

I guess as a feature request / potential enhancement for Augmentor to solve / (unless you can think of something better or maybe it already does this)
we need a way to guess (train a model) the transformation necessary to go from one transformation to the other.
eg. given a view is transformed from 
A -> B
// what was the transformation??? then from this glue / and some kalman filters - retrofit the point cloud. 

<img width="452" alt="screen shot 2017-10-03 at 9 46 16 am" src="https://user-images.githubusercontent.com/289994/31128416-b88a82c0-a81f-11e7-9fed-d62027045cd0.png">

Step 2 could be to isolate this to  bounding box. just thinking out loud here.

this is the code from video above
https://github.com/johndpope/ARKitExperiments

**Comment by johndpope** [comment]
rethinking this through - I suppose to infer a 3d point cloud - augmentor should actually have a 3d cloud out of the box / definitely scope creep here - augmentor3d.  maybe something for the backlog

**Comment by johndpope** [comment]
typing in 3d bounding box - (among other google results) returns this 
https://arxiv.org/abs/1612.00496

**Comment by johndpope** [comment]
https://github.com/smallcorgi/3D-Deepbox

**Comment by Evizero** [comment]
I am afraid this is currently beyond the scope of Augmentor. 

The proposed functionality seems a bit too vague or maybe special purpose, and the issue doesn't quite seem actionable. 

That said, it is possible for a user to write his/her custom Operations. So if you do end up implementing a working version of this and want to share it with the community, then we'd certainly review a PR. 

My personal suggestion is that this functionality should live (or at least start out) in its own dedicated package. This would also give you the freedom to experiment with its design

**Comment by johndpope** [comment]
fyi - distantly related / the guys at magic leap have possibly solved this problem. 
<img width="640" alt="screen shot 2017-10-10 at 2 27 25 pm" src="https://user-images.githubusercontent.com/289994/31403480-319b136c-adc7-11e7-8919-351d8c2f6216.png">
 https://arxiv.org/pdf/1707.07410.pdf

**Comment by johndpope** [comment]
fyi - https://github.com/charlesq34/pointnet2

**Comment by johndpope** [comment]
breaking 3D Object Detection  https://github.com/charlesq34/frustum-pointnets
