### ISSUE TITLE
Pipeline.image_generator() causes out  of range index

### ISSUE THREAD

**Issue by stnk20** [mdbloice/Augmentor#52]
This line causes out of range index:
https://github.com/mdbloice/Augmentor/blob/eae7394fdf6b92443f1d3dd66181ffda7a1f1cbf/Augmentor/Pipeline.py#L300

It should be:
`im_index = random.randint(0, len(self.augmentor_images-1)) `
Or clearer way:
`img= random.choice(self.augmentor_images)`

**Comment by mdbloice** [comment]
Hi there, 
thanks a lot for pointing this out, yeah that's a bug and is now fixed! 
M.
