### ISSUE TITLE
Zoom-out functionality available but turned off?

### ISSUE THREAD

**Issue by eddiesmo** [mdbloice/Augmentor#53]
First thing - thanks for this great repo!

The input for the zoom operation is limited to min_factor>1. 
I actually needed to use it for a "zoom out" functionality and simply disabled the input check - then everything worked as expected. 
Should this input check even be there? I know for most users adding a black margin for the "zoom out" effect is unwanted, but they can simply only use min_factor>1 - no need to forbid it.
What do you think?

**Comment by luis1761** [comment]
Thanks, this is actually very useful to know.

**Comment by mdbloice** [comment]
Hi @eddiesmo thanks for taking the time to make an issue - yeah you are right, I wonder though if doesn't make more sense to also give the option of filling that space with pixels that are of the same colour as the border of the original image. Anyway, yes, at a minimum I should allow zooming of a factor < 1, I'll change this in an update soon. 
M.

**Comment by eddiesmo** [comment]
Hi again! After using the zoom out feature for a while I noticed that the zoomed out image was not always the same size as the input image, so I fixed the casting of crop parameters and now it's fine. See PR here: https://github.com/mdbloice/Augmentor/pull/54

**Comment by mdbloice** [comment]
@eddiesmo ok so with the merge I'll close this, thanks again!
