### ISSUE TITLE
param name out of sync with readme & code?

### ISSUE THREAD

**Issue by palaniraja** [mdbloice/Augmentor#58]
Hi,

Thank you for the library.

I was trying to run with my own sample found that, it seems there is some changes not getting reflected in [readme](https://github.com/mdbloice/Augmentor/blob/master/README.md)?

Eg., as of now [readme](https://github.com/mdbloice/Augmentor/blob/master/README.md) & [docs](http://augmentor.readthedocs.io/en/master/userguide/mainfeatures.html) site both says

`
p.rotate(probability=0.7, max_left=10, max_right=10)
p.zoom(probability=0.5, min_scale=1.1, max_scale=1.5)

`
but i found out that the arguments have a different name (based on [autogenerated documentation](http://augmentor.readthedocs.io/en/master/code.html))

`
p.rotate(probability=0.7, max_left_rotation=10, max_right_rotation=10)
p.zoom(probability=0.5, min_factor=1.1, max_factor=1.5)
`

**Comment by mdbloice** [comment]
Hi, right, yes indeed, I will fix that with the next release :-) 
Thanks for the heads up! 
M.
