### ISSUE TITLE
Perform image operations in-memory

### ISSUE THREAD

**Issue by Evizero** [mdbloice/Augmentor#6]
It should not be default that images need to be stored to disk. Instead the operations should be performed in-memory such that operations can be chained easily

**Comment by Evizero** [comment]
@jonny911 @mdbloice Is this issue done and can be closed?

**Comment by lradacher** [comment]
@mdbloice  @Evizero @jonny911 I'm not quite sure if we implemented this issue sufficient, we could discuss this at the next meeting?
