### ISSUE TITLE
module 'Augmentor' has no attribute 'Pipeline'

### ISSUE THREAD

**Issue by agcala** [mdbloice/Augmentor#60]
Thanks for the wonderful library. But I am having an issue here. First time it worked alright but now as soon as I import Augmentor in Python I get the message

`builtins.AttributeError: module 'Augmentor' has no attribute 'Pipeline'`

Is there anything I can do about that?

**Comment by agcala** [comment]
I found the cause of the error. Thank you very much

**Comment by DonghunP** [comment]
Could you write solution how you solve the problem?? Thanks.
