### ISSUE TITLE
How to pass an image path as parameter and only preprocess it?

### ISSUE THREAD

**Issue by Kongsea** [mdbloice/Augmentor#62]
It seems Augmentor needs a work directory as the parameter and it will preprocess all files in it.
However, we always need to preprocess a specific image and use the image path as the parameter.
So how to use Augmentor in this situation?
Thank you.

**Comment by mdbloice** [comment]
Hi there, the best thing to do would be to pass the single image as an array. So create a pipeline object without specifying an image directory:

```python
import Augmentor
import numpy as np
from PIL import Image
# Create a Pipeline object without specifying a directory:
p = Augmentor.Pipeline()
# Add operations to the pipeline object as per usual:
p.rotate(probability=1, max_left_rotation=5, max_right_rotation=5)
```
and then pass an image as an array to the function `sample_with_array()`:

```python
img = Image.open("/tmp/test.JPEG")
img_array = np.asarray(img)
img_augmented = p.sample_with_array(img_array)
```
The image contained in `img_augmented` is an image in PIL format.

Admittedly this is not very intuitive, I'll try to fix that for a future version. Also the documentation for this functionality is sparse, I'll fix that too in an upcoming version.

M.

**Comment by Kongsea** [comment]
Thank you.
Look forward to the new version.

**Comment by mhnatiuk** [comment]
Hi,
I need to use Augmentor to process images file-by-file (i am generating artifical dataset and I have to do more operations than just augmenting). Im doing exactly what you posted above, however for
`augmentation_pipeline.sample_with_array(np.asarray(img))` (a numpy array) I get error:
```  File "/env/lib/python3.6/site-packages/Augmentor/Pipeline.py", line 239, in _execute
    return images[0]  # Here we return only the first image for the generators.
IndexError: list index out of range
```

**Comment by unnir** [comment]
@mhnatiuk 

you can do it like this:

```python
import Augmentor
import numpy as np
from PIL import Image
# Create a Pipeline object without specifying a directory:
p = Augmentor.Pipeline()
# Add operations to the pipeline object as per usual:
p.rotate(probability=1, max_left_rotation=5, max_right_rotation=5)
```

And then change your image:
`p.sample_with_array((X_train[0].reshape(480,480)))`

If it does not work, check this: 
https://github.com/mdbloice/Augmentor/issues/90

**Comment by ddfabbro** [comment]
I used [`p._execute_with_array`](https://github.com/mdbloice/Augmentor/blob/master/Augmentor/Pipeline.py#L283-L300) instead

```
img = Image.open("/tmp/test.JPEG")
img_array = np.asarray(img)
img_augmented = p._execute_with_array(img_array)
```
