### ISSUE TITLE
Option for absolute output path

### ISSUE THREAD

**Issue by sebastianheinz** [mdbloice/Augmentor#63]
Hi, 

currently, only a relative output path can be defined in `Pipeline()`. It would be helpful to be able to specify an absolute output path.

Cheers

**Comment by mdbloice** [comment]
Hi, thanks for making this issue,

What OS are you using? Under Linux if I do something like this:

```python
p = Augmentor.Pipeline("../augmentor_data_tests/isbi/data", output_directory="/tmp/")
```
```
Initialised with 2700 image(s) found.
Output directory set to /tmp/.
```

it works fine and outputs to the `/tmp` directory when calling `sample()`.

M.

**Comment by sebastianheinz** [comment]
Hi,

I am using OSX High Sierra 10.13.2

If I am replicating your minimal example, the message "Output directory set to /tmp/." does not show up. Seems to be an OS issue. Can you replicate the issue on OSX?

Cheers,
Sebastian

**Comment by mdbloice** [comment]
Hi,

OK so I just tested in on OSX 10.13.2, and it seems to work for me:

```
p = Augmentor.Pipeline("/Users/Marcus/Augmentor-Image-Tests/", output_directory="/tmp/")
Initialised with 2 image(s) found.
Output directory set to /tmp/.
```
Maybe try updating your version of Augmentor using `pip install Augmentor --upgrade`?

**Comment by sebastianheinz** [comment]
Hi, 

I've updated the package, now its working fine! Thank you!

Cheers
Sebastian
