### ISSUE TITLE
Pipelining multiple image with a probability of 1.0 to trigger each function

### ISSUE THREAD

**Issue by gauthiermartin** [mdbloice/Augmentor#69]
This is actually more a question then an issue.

I was wondering if their was an existing feature that grants us the ability to trigger each augmentor function on a set of images with a percentage of 100% in a way that every image in a dataset for exemple get generated for each available function of augmentor ... if not is their an easy way you could think of for doing this.

**Comment by Evizero** [comment]
in the sense of exhausting all possible paths through the pipeline to end up with all possible output images somewhere?

**Comment by gauthiermartin** [comment]
Yeah that is what i meant.

**Comment by mdbloice** [comment]
Currently there is no way to do this, but I think realistically you'd end up with far too many images, especially if you had more than a few operations in the pipeline...
