### ISSUE TITLE
Inside output folder an empty directory named "0" is created

### ISSUE THREAD

**Issue by abes975** [mdbloice/Augmentor#71]
While I processed a batch of multiple files in the output folder besides output files an empty directory with name "0" is created.
Same things does not happen if I have only 1 file to be processed inside my Pipeline.

This is a small reproducer

```
pipeline = Augmentor.Pipeline(source_directory="my_input",
                    output_directory="test_out", save_format="PNG")
        pipeline.random_distortion(probability=1, grid_width=3, grid_height=4, magnitude=3)
        pipeline.sample(100)
```

in this case folder 'my_input' contains multiple image files.

**Comment by mdbloice** [comment]
This has already been fixed, but is not in the version on PyPI just yet. I am going to update Augmentor to a new version in this week, it's part of a larger update - hence the delay!

**Comment by rojinsafavi** [comment]
Hello,
I am also working on a two-class classification problem, and in the output folder, the folder zero and one are both empty
