### ISSUE TITLE
Possible to run multiple pipeline at the same time

### ISSUE THREAD

**Issue by gauthiermartin** [mdbloice/Augmentor#80]
I was wondering if it was possible to run multiple pipeline at the same time 

Here is what im trying to achieve, we are trying to create multiple pipeline for each of our classes and then trigger random augmentation on each of them now we run on job after the other but is it possible to run like 2 or 3 at once ?

**Comment by mdbloice** [comment]
I guess there is nothing stopping you running several instances of Python and running several pipelines concurrently, is that what you mean? I am not sure if running them concurrently would actually make them finish faster, but it might.

**Comment by gauthiermartin** [comment]
Actually it's seem that the augmentation is made on a single core ... it does not use all thread on my cpu.
So i was wondering if there was a way to use all available power and augment multiple class at the same time

**Comment by mdbloice** [comment]
Yeah maybe using multiple instances of Python will use more of your cores, I am not actually sure about that. It could. You'd need to really use multiple Python instances though, and not just run a few pipelines concurrently somehow in one Python instance.
