### ISSUE TITLE
Use data.frame, dict, or list as pipeline input

### ISSUE THREAD

**Issue by kmader** [mdbloice/Augmentor#94]
It would be great if you could feed an ```Augmentor.Pipeline``` with other data sources like data.frames, dicts or lists for data that are not organized nicely in folders or where the categorical information looks different

**Comment by kmader** [comment]
An example of where this is helpful is the mammography dataset where you get a csv file describing each image 

https://www.kaggle.com/kmader/high-res-pretrained-vgg16-for-mammography

or the NIH Chest X-Ray Dataset

https://www.kaggle.com/nih-chest-xrays/data

**Comment by mdbloice** [comment]
Hi @kmader, sorry for the delays and thanks a great deal for your efforts - I just merged your PR, and I'll upload a new version with various other fixes to PyPI hopefully today!
