### ISSUE TITLE
README Quick Start Guide referencing max_right instead of max_right_rotation

### ISSUE THREAD

**Issue by ccatalfo** [mdbloice/Augmentor#96]
I noticed when first starting to use this awesome project that the Quick Start Guide still uses `max_right` and `max_left` parameters to rotate method whereas they seem to have been renamed to `max_right_rotation` and `max_left_rotation`.

I was momentarily tripped up when following the Quick Start Guide until I realized what the issue was.

**Comment by ccatalfo** [comment]
I issued a PR to fix this: https://github.com/mdbloice/Augmentor/pull/97.

**Comment by mdbloice** [comment]
Hi @ccatalfo thanks a lot, but this was actually just addressed with PR #93 which i merged a few minutes ago :-)

**Comment by ccatalfo** [comment]
@mdbloice ah, missed that then.   Thanks.
